apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-gateway-config
  namespace: observability
data:
  otel-gateway.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_mib: 400

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"

      # Debug (optional)
      debug:
        verbosity: detailed

    service:
      pipelines:

        metrics:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [prometheusremotewrite, debug]

