apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  otel-collector-config.yaml: |
    receivers:

      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch: {}

    exporters:
      otlp:
        endpoint: otel-gateway.observability.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
      
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
