apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch: {}

    exporters:
      logging:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]

        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
