apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-gateway
  namespace: observability
  labels:
    release: observability   # REQUIRED MATCH
spec:
  selector:
    matchLabels:
      app: otel-gateway
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
