apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/grafana-community/helm-charts
    targetRevision: main
    path: charts/grafana
    helm:
      releaseName: grafana
      values: |
        persistence:
          enabled: true
          size: 500Mi
          accessModes:
            - ReadWriteOnce

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
